version: '3.1'
services:
  db:
    container_name: teste_trampay
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_trampay
    ports:
      - "5432:5432"
    volumes:
      - db-teste-trampay:/var/lib/postgresql/data
volumes:
  db-teste-trampay: